[build-system]
requires = ["hatchling>=1.18"]
build-backend = "hatchling.build"

[project]
name = "context-sdk"
version = "0.1.0"
description = "Super simple Context SDK"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name = "Arav", email = "" }
]
keywords = ["context", "sdk"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/"
Repository = "https://github.com/"

[tool.hatch.build.targets.wheel]
packages = ["src/context_sdk"]


